export const CHECK_EMAIL = 'CHECK_EMAIL'
export const CHECK_PASSWORD = 'CHECK_PASS'
export const SIGN_IN = 'SIGN_IN'
export const ALERT_OK = 'ALERT_OK'
export const REMEMBER_USER = 'REMEMBER_USER'
export const REMEMBER_PASS = 'REMEMBER_PASS'